openapi: 3.0.1
info:
  title: monster-nalfeshnee
  x-cortex-tag: monster-nalfeshnee
  x-cortex-custom-metadata:
    alignment: chaotic-evil
    type: fiend
    challenge_rating: 13
    legendary: true
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-nalfeshnee
      alias: github-token-test
